management:
  endpoint:
    health:
      show-details: always
  security:
    enabled: false
  health:
    db:
      enabled: true
    diskspace:
      enabled: true

spring:
  profiles:
    active: dev
server:
  port: 8085
